name: grocery_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  appwrite: ^11.0.0
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  persistent_bottom_nav_bar: ^5.0.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

flutter_native_splash:
  color: "#53B175"
  image: assets/images/splash_logo.png

  android_12: null
dev_dependencies:
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/launch_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Medium.ttf
          weight: 500

        #   style: normal
        - asset: fonts/Gilroy-Semibold.ttf
          weight: 700

        - asset: fonts/FontsFree-Net-Gilroy-Bold.ttf
          weight: 900
